# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71ade40d0a3d734e4d7646f13926979130123f286f671a28065dc81b51f52ad53b4c8be82466109740d99f0d76b1d50876f9764a1dd34e5f91e2e165cd340937

test:
  secret_key_base: 80f259b242c66694295e92db762fe19250342daa8d993d56d8060eb5de46879dc625a582417fcd1ad5ef417735eb7496e798fb214ca661611e4049b99cf552bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
